// <auto-generated />
using System;
using CodeFirst1710.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirst1710.Migrations
{
    [DbContext(typeof(TvcDay09LabCFContext))]
    partial class TvcDay09LabCFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeFirst1710.Models.TvcLoai_San_Pham", b =>
                {
                    b.Property<long>("tvcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("tvcId"));

                    b.Property<string>("tvcMaLoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("tvcTrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("tvcId");

                    b.HasIndex("tvcMaLoai")
                        .IsUnique();

                    b.ToTable("TvcLoai_San_Pham");
                });

            modelBuilder.Entity("CodeFirst1710.Models.TvcSan_Pham", b =>
                {
                    b.Property<int>("tvcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tvcId"));

                    b.Property<decimal>("tvcDonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("tvcHinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("tvcLoaiSanPhamId")
                        .HasColumnType("bigint");

                    b.Property<long?>("tvcLoai_San_PhamtvcId")
                        .HasColumnType("bigint");

                    b.Property<string>("tvcMaSanPham")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("tvcSoLuong")
                        .HasColumnType("int");

                    b.Property<string>("tvcTenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("tvcId");

                    b.HasIndex("tvcLoai_San_PhamtvcId");

                    b.ToTable("TvcSan_Pham");
                });

            modelBuilder.Entity("CodeFirst1710.Models.TvcSan_Pham", b =>
                {
                    b.HasOne("CodeFirst1710.Models.TvcLoai_San_Pham", "tvcLoai_San_Pham")
                        .WithMany("tvcSan_Phams")
                        .HasForeignKey("tvcLoai_San_PhamtvcId");

                    b.Navigation("tvcLoai_San_Pham");
                });

            modelBuilder.Entity("CodeFirst1710.Models.TvcLoai_San_Pham", b =>
                {
                    b.Navigation("tvcSan_Phams");
                });
#pragma warning restore 612, 618
        }
    }
}
